# Dependabot configuration for KasStamp
version: 2
updates:
  # JS Core / SDK
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kasstamp"
    assignees:
      - "kasstamp"
    commit-message:
      prefix: "chore(js)"
      prefix-development: "chore(js)"
    labels:
      - "dependencies"
      - "js"

  # Web Frontend
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kasstamp"
    assignees:
      - "kasstamp"
    commit-message:
      prefix: "chore(web)"
      prefix-development: "chore(web)"
    labels:
      - "dependencies"
      - "web"

  # Root / Global Tooling
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kasstamp"
    assignees:
      - "kasstamp"
    commit-message:
      prefix: "chore(global)"
      prefix-development: "chore(global)"
    labels:
      - "dependencies"
      - "global"
