# Dependabot configuration for KasStamp
version: 2
updates:
  # JavaScript packages
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kasstamp"
    assignees:
      - "kasstamp"
    commit-message:
      prefix: "chore(global)"
      prefix-development: "chore(global)"
      include: "none"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "typescript"
          - "babel*"
        update-types:
          - "minor"
          - "patch"
      crypto-dependencies:
        patterns:
          - "@noble/*"
          - "@scure/*"
        update-types:
          - "minor"
          - "patch"

  # Web package
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kasstamp"
    assignees:
      - "kasstamp"
    commit-message:
      prefix: "chore(global)"
      prefix-development: "chore(global)"
      include: "none"
    labels:
      - "dependencies"
      - "web"
    groups:
      dev-dependencies:
        patterns:
          - "vite*"
          - "vitest*"
          - "@types/*"
          - "eslint*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      ui-dependencies:
        patterns:
          - "react*"
          - "@radix-ui/*"
          - "tailwindcss"
        update-types:
          - "minor"
          - "patch"
