export default function PrivacyPage() {
  return (
    <div className="mx-auto grid w-full max-w-3xl gap-6 px-3 py-8 sm:px-6">
      <div className="grid gap-2">
        <h1 className="font-semibold">Privacy Policy</h1>
        <p className="text-gray-600">Last updated: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="box">
        <div className="grid gap-4 text-sm text-gray-700">
          <section>
            <h2 className="mb-2 text-lg font-medium">1. Introduction</h2>
            <p>
              This Privacy Policy explains how KasStamp (“we”, “us”, “our”) handles personal data in
              connection with the use of our open-source, client-side service. We take your privacy
              seriously and are committed to protecting it in accordance with the General Data
              Protection Regulation (GDPR) and applicable German and European data protection laws.
              By using KasStamp, you agree to this Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">2. Scope of This Policy</h2>
            <p>
              This policy applies to the use of the KasStamp website and the software provided
              through it. It explains how we handle personal data, what data is (or is not)
              processed, and how you can exercise your rights. KasStamp is a free, open-source,
              non-commercial tool designed to operate entirely on your local device without backend
              processing.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">3. Data Processing Overview</h2>
            <p>
              KasStamp does not collect, store, or process any personal data on our servers. All
              cryptographic processing, data preparation, and interaction with the Kaspa blockDAG
              occur locally within your browser environment. We do not receive or have access to any
              files, metadata, cryptographic keys, or blockchain transactions you create or submit.
            </p>
            <p className="mt-2">
              The only data our infrastructure handles is the static website code, which is served
              when you load the KasStamp application. Once the site is loaded, no further
              communication with our servers takes place.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">4. Hosting and Log Data</h2>
            <p>
              Our website is hosted by <strong>Host Europe GmbH</strong> in Germany. When you visit
              the website, standard HTTP access logs may be automatically generated by the hosting
              provider. These logs typically include your IP address, date and time of access,
              browser type, operating system, and requested resources.
            </p>
            <p className="mt-2">
              Such logs are processed solely for technical reasons (e.g., ensuring website
              availability and security) and are automatically deleted after a short retention
              period. We do not use these logs for analytics, profiling, or marketing purposes.
              Legal basis for this processing is Article 6(1)(f) GDPR (legitimate interest in
              providing a secure and stable website).
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">5. No Cookies, Analytics, or Tracking</h2>
            <p>
              KasStamp does not use cookies, analytics services, advertising tools, or other
              tracking technologies. We do not collect any usage statistics or behavioral data.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">6. Blockchain Data and Public Networks</h2>
            <p>
              When using KasStamp to anchor data to the Kaspa blockDAG, certain technical
              information is published to a public and decentralized network beyond our control.
              This may include cryptographic proofs derived from your files. Once submitted,
              blockchain data is immutable and may be accessible globally.
            </p>
            <p className="mt-2">
              You are solely responsible for the content you anchor and for ensuring that it does
              not contain personal data or violate applicable data protection or criminal laws. We
              cannot remove or alter any data recorded on the blockchain.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">7. Your Data Protection Rights</h2>
            <p>
              Because KasStamp does not process personal data beyond transient server logs, most
              GDPR rights (such as access, rectification, or erasure) do not apply in the context of
              our Service. However, if you believe that we process personal data about you, you have
              the following rights under GDPR:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>Right of access (Art. 15 GDPR)</li>
              <li>Right to rectification (Art. 16 GDPR)</li>
              <li>Right to erasure (Art. 17 GDPR)</li>
              <li>Right to restriction of processing (Art. 18 GDPR)</li>
              <li>Right to data portability (Art. 20 GDPR)</li>
              <li>Right to object (Art. 21 GDPR)</li>
              <li>Right to lodge a complaint with a supervisory authority (Art. 77 GDPR)</li>
            </ul>
            <p className="mt-2">
              In Germany, the competent supervisory authority is generally the data protection
              authority of your federal state (<em>Landesdatenschutzbehörde</em>).
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">8. Data Security</h2>
            <p>
              We implement appropriate technical and organizational measures to secure our website
              infrastructure and protect it from unauthorized access. However, because KasStamp
              operates client-side and interacts with decentralized networks, users are responsible
              for safeguarding their own devices, cryptographic keys, and data.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">9. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. The latest version will always be
              published on our website. Continued use of KasStamp following any changes constitutes
              acceptance of the revised policy.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-medium">10. Contact</h2>
            <p>
              For any inquiries regarding the privacy or this service, please contact us:
            </p>
            <div className="mt-2">
              <br />
              <p>Marcel Sangals and Tjark Fröse</p>
              <p>Am Knill 152, 22147 Hamburg</p>
              <br />
              <p>Website: https://kasstamp.com</p>
              <p>Email: kasstamp@gmail.com</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
